apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus-bigquery-exporter.fullname" . }}-queries
  labels:
    {{- include "prometheus-bigquery-exporter.labels" . | nindent 4 }}
data:
{{- $files := .Files.Glob "queries/*" }}
{{- $root := . -}}
{{- range $path, $_ := $files }}
  {{ base $path }}: |-
{{ $root.Files.Get $path | indent 4 }}
{{- end }}
